spring.application.name=eats_hub_catalog

# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
#spring.data.mongodb.database=catalog

# spring.mongodb.host=localhost
# spring.mongodb.port=27017
# spring.mongodb.username=
# spring.mongodb.password=
# spring.mongodb.database=catalog
# spring.mongodb.authentication-database=
# spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb=DEBUG

#spring.data.mongo.url= mongodb://master:fabiomongo@localhost:27017/catalog?authSource=admin