mongodb.host=localhost
mongodb.port=27017
mongodb.username=master
mongodb.password=fabiomongo
mongodb.database=catalog
mongodb.authentication-database=admin

mongodb.maxPoolSize=20
mongodb.minPoolSize=10
mongodb.maxConnectionLifeTime=60000